/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.arteymix.peoplecounter;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author guillaume
 */
public class PeopleCounterJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PeopleCounterJFrame
     */
    public PeopleCounterJFrame() {
        initComponents();
        Place.instance().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                tIDInput.setText("");
                tCount.setText(Integer.toString(Place.instance().getCount()));
                tCountIn.setText(Integer.toString(Place.instance().getCountIn()));
                tCountOut.setText(Integer.toString(Place.instance().getCountOut()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tIDInput = new javax.swing.JTextField();
        bScan = new javax.swing.JButton();
        bScanIn = new javax.swing.JButton();
        bScanOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tCount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tCountIn = new javax.swing.JTextField();
        tCountOut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PeopleCounter");
        setMinimumSize(new java.awt.Dimension(694, 523));

        jTable1.setModel(Place.instance());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tIDInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tIDInputKeyReleased(evt);
            }
        });

        bScan.setText("Scan");
        bScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bScanActionPerformed(evt);
            }
        });

        bScanIn.setText("Scan in");
        bScanIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bScanInActionPerformed(evt);
            }
        });

        bScanOut.setText("Scan out");
        bScanOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bScanOutActionPerformed(evt);
            }
        });

        jLabel1.setText("Count");

        tCount.setEditable(false);

        jLabel2.setText("Count in");

        tCountIn.setEditable(false);

        tCountOut.setEditable(false);

        jLabel3.setText("Count out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tIDInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bScan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bScanIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bScanOut))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCountIn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCountOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bScan)
                    .addComponent(bScanIn)
                    .addComponent(bScanOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tCountIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tCountOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lError, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bScanInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bScanInActionPerformed
        try {
            Place.instance().scanIn(tIDInput.getText());
            lError.setText("");
        } catch (NotMatchingException nme) {
            lError.setText("N'est pas dans la liste");
        }

        jTable1.updateUI();

    }//GEN-LAST:event_bScanInActionPerformed

    private void bScanOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bScanOutActionPerformed
        try {
            Place.instance().scanOut(tIDInput.getText());
            lError.setText("");
        } catch (NotMatchingException nme) {
            lError.setText("N'est pas dans la liste");
        }
        jTable1.updateUI();

    }//GEN-LAST:event_bScanOutActionPerformed

    private void bScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bScanActionPerformed
        try {
            Place.instance().scan(tIDInput.getText());
            lError.setText("");
        } catch (NotMatchingException nme) {
            lError.setText("N'est pas dans la liste");
        }
        jTable1.updateUI();

    }//GEN-LAST:event_bScanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        tIDInput.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
    }//GEN-LAST:event_jTable1MouseClicked

    private void tIDInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIDInputKeyReleased
        System.out.println(evt.getKeyCode());
        // Si on pèse sur Enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bScanActionPerformed(null);
        }
    }//GEN-LAST:event_tIDInputKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeopleCounterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeopleCounterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeopleCounterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeopleCounterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PeopleCounterJFrame main = new PeopleCounterJFrame();
                main.setVisible(true);
                JFileChooser jfc = new JFileChooser();

                switch (jfc.showOpenDialog(main)) {
                    case JFileChooser.APPROVE_OPTION:
                        // Fill up the match against hashset
                        try {
                            FileInputStream fis = new FileInputStream(jfc.getSelectedFile());
                            BufferedReader isr = new BufferedReader(new InputStreamReader(fis));
                            String line;
                            while ((line = isr.readLine()) != null) {
                                Place.instance().mMatchAgainst.add(line);
                            }

                        } catch (FileNotFoundException ex) {
                            JOptionPane.showMessageDialog(main, "", "Fichier non trouvé", JOptionPane.ERROR_MESSAGE);
                            Logger.getLogger(PeopleCounterJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(PeopleCounterJFrame.class.getName()).log(Level.SEVERE, null, ex);
                            System.exit(0);
                        }
                        break;
                    case JFileChooser.CANCEL_OPTION:
                        JOptionPane.showMessageDialog(main, "Aucun fichier n'a été spécifié. Le programme va quitter.", "Aucun fichier n'a été spécifié. Le programme va quitter.", JOptionPane.ERROR_MESSAGE);
                        System.exit(0);



                }




            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bScan;
    private javax.swing.JButton bScanIn;
    private javax.swing.JButton bScanOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lError;
    private javax.swing.JTextField tCount;
    private javax.swing.JTextField tCountIn;
    private javax.swing.JTextField tCountOut;
    private javax.swing.JTextField tIDInput;
    // End of variables declaration//GEN-END:variables
}
